### ISSUE TITLE
Building highly-performant backend with Hasura

### ISSUE THREAD

**Issue by beerose** [ChopChopOrg/academy#7]
# Building highly-performant backend with Hasura

##  🦸‍♂️ Who's the speaker?

- **your full name**: Aleksandra Sikora
- **social media link**: https://twitter.com/aleksandrasays

### Few words about you

Software Engineer @ Hasura. Web technologies and functional programming enthusiast. 

##  🎤 What's the talk?

- **estimated duration**: 40 min
- **format** live-coding/lecture

### Tell us more about the talk

During this talk, you will learn how to easily add backend to the existing React app using http://hasura.io open-source platform. We'll look at what Hasura offers and how to make the most of it. You will also learn the basics of GraphQL and how to integrate your frontend with GraphQL server.

### Do you mind if we record or take photos of the event?

Not at all.

### Is there anything we can help you with?

**Comment by chop-chop-org** [comment]
Hej Ola, dzieki wielkie za super propozycje! Zapraszamy Cię z tym talkiem na meetup marcowy :) Szczegóły dogadajmy na privie ;)
Janek & reszta organizatorów

**Comment by hasparus** [comment]
Thanks! Your talk went really well!
